export enum ErrorCode {
  // Auth & Identity
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  ACCOUNT_NOT_ACTIVE = 'ACCOUNT_NOT_ACTIVE',
  ACCOUNT_ALREADY_VERIFIED = 'ACCOUNT_ALREADY_VERIFIED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // OTP
  INVALID_OR_EXPIRED_OTP = 'INVALID_OR_EXPIRED_OTP',
  OTP_MAX_ATTEMPTS_EXCEEDED = 'OTP_MAX_ATTEMPTS_EXCEEDED',
  OTP_RESEND_COOLDOWN = 'OTP_RESEND_COOLDOWN',

  // Token & Session
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',

  // Security & Throttling
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  FORBIDDEN = 'FORBIDDEN',

  // Generic & Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}
